### ISSUE TITLE
Using the "typing" package causes conflicts in Python 3.7

### ISSUE THREAD

**Issue by danielRicardo** [aws/sagemaker-training-toolkit#60]
**Describe the bug**
There is a known conflict between the built-in `typing` implementation in Python 3.7 and the `typing` library in pipy. 
See example [here](https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry).
The `typing` package is included in the `setup.py`, but not actually used throughout the code.
Therefore, it causes a conflict with Python 3.7 which can be avoided.

**To reproduce**
Create a training code in Python 3.7 which includes type hints for abstract classes, and try invoking it.
 
**Expected behavior**
The code should run without problems.

**Screenshots or logs**
You get the following error: 
`AttributeError: type object 'Callable' has no attribute '_abc_registry'`

**System information**
I'm using a custom Docker image based on the `sagemaker-scikit-learn-container` with the only change being that I upgraded it to Python 3.7.
The same issue happened both when I used the original version which still uses the `sagemaker-container` package, and the [branch](https://github.com/aws/sagemaker-scikit-learn-container/pull/38) which switches to the `sagemake-training-toolkit`

Fixing this is a simple matter of removing `typing` from the installed packages in `setup.py`

**Comment by ajaykarpur** [comment]
Hi @danielRicardo, thanks for bringing this to our attention. Since this toolkit supports Python 2.7, we use the `typing` package from PyPI to backport the functionality. This is used in several places throughout the code.

To resolve the conflict with the built-in `typing` implementation in Python 3.7, we'll need to remove all usage of `typing` and remove the dependency from setup.py as you described. I'll submit a pull request for this soon.

**Comment by ajaykarpur** [comment]
The fix for this issue has been released in https://github.com/aws/sagemaker-training-toolkit/releases/tag/v3.5.1
